### ISSUE TITLE
the new update seems to have broken controller support in tomb raider I

### ISSUE THREAD

**Issue by F3arM3** [luxtorpeda-dev/packages#1026]
### Game

Tomb Raider I

### Engine

Open Lara

### Linux Distribution

Ubuntu 22.04.3 LTS

### Luxtorpeda Version

67.1.0

### Bug description

The game doesn't respond to B, R & L Shoulder, R & L Trigger, and the right analogue stick inputs even after reinstalling the game, luxtorpeda and rebooting my Pc. I know it isn't my PC/Controller because games like powerwash simulator still work with the controller and keyboard inputs work in the game as well

### Steps To Reproduce

update luxtorpeda

### Expected Behavior

the controller should work in the game

**Comment by F3arM3** [comment]
here is the event log, hopefully it shows something
[tomb3.zip](https://github.com/luxtorpeda-dev/packages/files/13372557/tomb3.zip)

**Comment by d10sfan** [comment]
Does the controller work if you go back to the previous luxtorpeda version?

**Comment by d10sfan** [comment]
I found the issue, the new luxtorpeda update included an update to godot, which had a regression somehow in controller support. I've downgraded and a new version should be available shortly as 67.1.1. That should fix the issue.

**Comment by F3arM3** [comment]
It didn't fix it, also I tried going back to 67.0.0 and it won't start even if I completely reinstall tomb raider

**Comment by d10sfan** [comment]
It's working ok for me with 67.1.1, can you confirm that you're on that version?

If so, can you provide a log?

**Comment by F3arM3** [comment]
I am on 67.1.1
and here is a log with a fresh download of tomb raider and luxtorpeda and reboot of my pc
[tomb4.txt](https://github.com/luxtorpeda-dev/packages/files/13383264/tomb4.txt)

**Comment by F3arM3** [comment]
wait where would the godot config be stored on my pc? maybe it didn't downgrade for whatever reason with 67.1.1?

**Comment by d10sfan** [comment]
I replicated the problem and then updated to the new version and it worked, although there's a folder at ~/.local/share/Luxtorpeda/ that you can try deleting.

**Comment by F3arM3** [comment]
nope, still no luck

**Comment by F3arM3** [comment]
i figured it out, steam input is now translating my controller as keyboard inputs! in the steam settings it has xinput b mapped to end key but open lara has roll mapped to A, same with the other keys. 
So the real issue is that for whatever reason open lara isn't responding to mycontroller directly even if I disable steam input. and the open lara keyboard controls don't match steam input

**Comment by F3arM3** [comment]
Maybe a fix would be to have people disable steam input and have open lara run its own controller software

**Comment by d10sfan** [comment]
Ah ok, sounds like it's because steam input is overriding your controller

**Comment by d10sfan** [comment]
Thanks for the details there
