### ISSUE TITLE
UnrealTournament (1999) Not Launching

### ISSUE THREAD

**Issue by Sojiro84** [luxtorpeda-dev/packages#505]
### Linux Distribution

EndeavourOS (Arch based)

### Luxtorpeda Version

36

### Bug description

UnrealTournament launches and I hear sound, but the screen stay's black.

I have added the log.

### Steps To Reproduce

Launch the game and the bug happens.

### Expected Behavior

I expected to see the game and not a black screen.

### Relevant log output

```shell
run: "./run-ut99-469b.sh" with args: [] []
WARNING: using preference directory: /home/sojiro/.utpg/System/
WARNING: Using system ini file: /home/sojiro/.local/share/Steam/steamapps/common/Unreal Tournament/linuxdata-469b/System/UnrealTournament.ini
WARNING: Using user ini file: /home/sojiro/.local/share/Steam/steamapps/common/Unreal Tournament/linuxdata-469b/System/User.ini
XOpenGL: Failed linking DrawSimpleProg
XOpenGL: Failed linking DrawTileProg
XOpenGL: Failed linking DrawComplexProg
XOpenGL: Failed linking DrawGouraudProg
Installing breakpad exception handler for appid(gameoverlayui)/version(20210923143515)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
Installing breakpad exception handler for appid(gameoverlayui)/version(1.0)
./ut: 79: ./ut: setxkbmap: not found
./ut: 1: ./ut: setxkbmap: not found
dropping: "/run/user/1000/luxtorpeda/13240.pid"
```

**Comment by Sojiro84** [comment]
I have to use the runtime, because if I use the non-runtime version, nothing happens at all. This is the log of the non-runtime version:

```
GameAction [AppID 13240, ActionID 4] : LaunchApp changed task to ProcessingInstallScript with ""
Error: Custom { kind: Other, error: "iscriptevaluator ignorning" }
GameAction [AppID 13240, ActionID 4] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 13240, ActionID 4] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 13240, ActionID 4] : LaunchApp waiting for user response to CreatingProcess ""
GameAction [AppID 13240, ActionID 4] : LaunchApp continues with user response "CreatingProcess"
/bin/sh\0-c\0/home/sojiro/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=13240 -- '/usr/share/steam/compatibilitytools.d/luxtorpeda/luxtorpeda-original'/../luxtorpeda wait-before-run '/home/sojiro/.local/share/Steam/steamapps/common/Unreal Tournament/System/UnrealTournament.exe'\0
Game process added : AppID 13240 "/home/sojiro/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=13240 -- '/usr/share/steam/compatibilitytools.d/luxtorpeda/luxtorpeda-original'/../luxtorpeda wait-before-run '/home/sojiro/.local/share/Steam/steamapps/common/Unreal Tournament/System/UnrealTournament.exe'", ProcID 141399, IP 0.0.0.0:0
SpawnProcessInternal: chdir() failed, errno 2
ERROR: ld.so: object '/home/sojiro/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 13240, ActionID 4] : LaunchApp changed task to WaitingGameWindow with ""
ERROR: ld.so: object '/home/sojiro/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/sojiro/.local/share/Steam/ubuntu12_32/gameoverlayrenderer.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS32): ignored.
GameAction [AppID 13240, ActionID 4] : LaunchApp changed task to Completed with ""
update_packages_json. "/home/sojiro/.cache/luxtorpeda/packages.json" does not exist
update_packages_json. downloading new packages.json
update_packages_json. new downloaded hash does not match
creating: "/run/user/1000/luxtorpeda/13240.pid"
steam_app_id: "13240"
original command: ["/home/sojiro/.local/share/Steam/steamapps/common/Unreal Tournament/System/UnrealTournament.exe"]
working dir: Ok("/home/sojiro/.local/share/Steam")
tool dir: "/usr/share/steam/compatibilitytools.d/luxtorpeda/luxtorpeda-original/.."
read err: Os { code: 2, kind: NotFound, message: "No such file or directory" }
dropping: "/run/user/1000/luxtorpeda/13240.pid"
Error: Custom { kind: Other, error: "missing info about this game" }
Game process removed: AppID 13240 "/home/sojiro/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=13240 -- '/usr/share/steam/compatibilitytools.d/luxtorpeda/luxtorpeda-original'/../luxtorpeda wait-before-run '/home/sojiro/.local/share/Steam/steamapps/common/Unreal Tournament/System/UnrealTournament.exe'", ProcID 141399 
Uploaded AppInterfaceStats to Steam
No cached sticky mapping in ActivateActionSet.
```

**Comment by d10sfan** [comment]
@Sojiro84 

The issue you were seeing with the non-runtime (original) one should be fixed now, next time you launch a game. There was an issue with the original's hash being incorrect, so it's been fixed on the server side.


Can you try the original version as a comparison to see if that works, as in try 469b on the original tool?

As well, what graphics driver type do you have, and do you have 32-bit versions of those installed?

**Comment by Sojiro84** [comment]
Tried the non-runtime bit still get the same error. Do I need to do something to force a refresh or something? Or maybe remove a cache directory?

I have multilib enabled. I am running AMD 5700XT on mesa.

**Comment by d10sfan** [comment]
@Sojiro84 No the engine itself should be the same on both in this particular case.

This sounds like it may be an issue with the game itself, you could try creating an issue here: https://github.com/OldUnreal/UnrealTournamentPatches/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

That's the project where the 469b patch comes from. If you do, let me know if they end up having any fix that I could provide in the engine for luxtorpeda, to make it easier to launch.
