### ISSUE TITLE
Doom II Changes

### ISSUE THREAD

**Issue by d10sfan** [luxtorpeda-dev/packages#714]
https://steamdb.info/app/2300/history/

Recently, the steam setup for Doom II was changed so that more exp packs were put under the umbrella of one game, so the luxtorpeda options should be updated to be able to match the launch options picked in steam (use the command match inside the options, so they pick the launch option in steam and then get the various doom engines)).

Verify what happens with the re-release (pathing may have been changed), make sure all original ones work. 

Then remove the old references to the older games (similar to the quake exp)

**Comment by d10sfan** [comment]
Done with the following commits:

https://github.com/luxtorpeda-dev/packages/commit/bc5ccb404fa88755df9a67b28b7bcf27ee4667ba
https://github.com/luxtorpeda-dev/packages/commit/9682987a377b365641242453a558ccb3ff35dcaa
https://github.com/luxtorpeda-dev/packages/commit/1aa554f47be9cc1e1b710c451b4b0858f182b3ce
https://github.com/luxtorpeda-dev/packages/commit/15eb1fc5b23f4b23a14328da708b618b7bd382c8
https://github.com/luxtorpeda-dev/packages/commit/480aecd8980a0d6927594e7b5a107ac463e38a3a
https://github.com/luxtorpeda-dev/packages/commit/284ca15cbd7aafceb39d55ba95930ce008538b6b
https://github.com/luxtorpeda-dev/packages/commit/5984f862900ced460873cecacb00e63b6a0b79ef

**Comment by vaibhavrmahadevan** [comment]
@d10sfan oh so the older standalone titles (Master Levels and Final Doom) will cease to have luxtorpeda support? :pensive:

**Comment by d10sfan** [comment]
@vaibhavrmahadevan I had assumed that they would be giving access to doom 2 for those who already own final doom, which does not appear to be the case. Doom 2 is on sale, but I will look into bringing support back for those titles.

**Comment by d10sfan** [comment]
@vaibhavrmahadevan Those should work again now, for those who do not own Doom II.

https://github.com/luxtorpeda-dev/packages/commit/bc0c986552ab7c85fbc587186f4d1be0d00f9f8b
https://github.com/luxtorpeda-dev/packages/commit/261ee41d16d0273371383360bbe500ab5456898e
https://github.com/luxtorpeda-dev/packages/commit/c7c8b1d64210a2e4b0c29c0f2053d92deba6b31d
https://github.com/luxtorpeda-dev/packages/commit/8a34863327e8d4afb93dc3945c4dd5586b53ec55

**Comment by vaibhavrmahadevan** [comment]
@d10sfan Thank you so much!

I really appreciated the move to simplify the store listings but I felt Final Doom and the Master Levels having their own play time separate from Doom II was better being the needless pedant that I am 😔

**Comment by vaibhavrmahadevan** [comment]
@d10sfan I am so sorry to trouble you again but the options for the Master Levels (9160) are not launching, one of the reasons I feel may be due to doom-complete.pk3 not being generated.

**Comment by d10sfan** [comment]
@vaibhavrmahadevan Could you provide a log of this? Easiest way to do that is to run steam in a terminal window and then attempt to launch the game.

**Comment by vaibhavrmahadevan** [comment]
@d10sfan [Master Levels for DOOM II.txt](https://github.com/luxtorpeda-dev/packages/files/9422874/Master.Levels.for.DOOM.II.txt)

**Comment by d10sfan** [comment]
@vaibhavrmahadevan Can you try it now? It looks like qzdl wasn't downloaded the most up to date version for master levels, which should be fixed now.

**Comment by vaibhavrmahadevan** [comment]
@d10sfan tried to launch all options two hours ago and just before but still not launching :(

**Comment by d10sfan** [comment]
@vaibhavrmahadevan Can you send me logs from trying with gzdoom?

**Comment by vaibhavrmahadevan** [comment]
@d10sfan [GZDoom.txt](https://github.com/luxtorpeda-dev/packages/files/9427043/GZDoom.txt)

**Comment by d10sfan** [comment]
@vaibhavrmahadevan That should be fixed about an hour after this comment. Let me know how it goes!

The problem was that the script wasn't setup as executable, when I copied the new one. It should be fixed now, thanks for the issue report.

**Comment by vaibhavrmahadevan** [comment]
@d10sfan yay! it worked!

I suspected the same while comparing the scripts with the ones in DOOM II and tried enabling it in the properties several times but alas :(
