### ISSUE TITLE
OpenMW does not start up

### ISSUE THREAD

**Issue by kaneyumin** [luxtorpeda-dev/packages#847]
### Game

The Elder Scrolls III: Morrowind

### Engine

OpenMW

### Linux Distribution

Nobara 37

### Luxtorpeda Version

Used both 59/61

### Bug description

The game does not launch after selecting an option on the luxtorpeda menu. The package for source port downloads fine and files are present in the game directory. I have reinstalled the game and tried a different drive with the same result.

### Steps To Reproduce

1. Launch game with luxtorpeda
2. Select either stable or latest version
3. Game does not launch

### Expected Behavior

Game launching.

### Additional Context

log:
[luxtorpeda.zip](https://github.com/luxtorpeda-dev/packages/files/10774966/luxtorpeda.zip)

**Comment by d10sfan** [comment]
@kaneyumin Could you take a screenshot of your directory listing for the morrowind game?

**Comment by kaneyumin** [comment]
![image](https://user-images.githubusercontent.com/85457501/219903055-bc21cd24-242d-43bb-9b8c-ae8e63d0fab7.png)

**Comment by d10sfan** [comment]
Interesting, like you said it does look like everything is there. Can you try the launcher option and provide the log? Curious if anything happens differently there.

**Comment by kaneyumin** [comment]
[luxtorpeda.zip](https://github.com/luxtorpeda-dev/packages/files/10775962/luxtorpeda.zip)

**Comment by d10sfan** [comment]
Are you able to play any other luxtorpeda-dev games?

Also, do you have a ~/.config/openmw folder? And if so, can you provide your openmw.cfg and openmw.log file there?

**Comment by d10sfan** [comment]
Can you try renaming/removing that openmw.cfg file and launching the openmw without launcher again and see what happens? There should be a bit more to that file, being generated from lux.

**Comment by kaneyumin** [comment]
The new file that gets created has the same contents as the previous one.

**Comment by d10sfan** [comment]
There should be more in the file, it seems like openmw-iniimporter is failing to run properly. Can you provide a log of you removing the file and then running again, that should show where it stopped.

Thanks

**Comment by kaneyumin** [comment]
This is the log after removing and relaunching it.
[luxtorpeda.zip](https://github.com/luxtorpeda-dev/packages/files/10786734/luxtorpeda.zip)

**Comment by d10sfan** [comment]
Could you try running steam in a terminal window, then launching the game and saving the output? I think there's some log statements in the shell script that aren't being seen in this log file

**Comment by kaneyumin** [comment]
19:40:06 [INFO] run: "./openmw.sh" with args: [] []
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
No openmw.cfg file detected, so creating and adding resources
Now running iniimporter
./openmw-iniimporter: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
19:40:06 [INFO] run returned with exit status: 127
Game process removed: AppID 22320 "LUX_WRITE_LOGGING=1 /home/kane/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=22320 -- /home/kane/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/kane/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kane/.local/share/Steam/compatibilitytools.d/luxtorpeda'/luxtorpeda.sh waitforexitandrun  '/home/kane/.local/share/Steam/steamapps/common/Morrowind/Morrowind Launcher.exe'", ProcID 198240 

The line that isn't picked up by the log is 

>./openmw-iniimporter: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory

**Comment by d10sfan** [comment]
Ah ok thanks, that helps solve that mystery.

Not sure why it's complaining about libbz2, since that should be part of the steam runtime.

Can you check the SteamLinuxRuntime_soldier/soldier_platform_0.20230117.0/files/lib/x86_64-linux-gnu/ folder, and see if you have a libbz2.so.1.0 file there?

**Comment by kaneyumin** [comment]
There is libbz2.so.1.0.4 . but not libbz2.so.1.0

**Comment by d10sfan** [comment]
There's also a folder that'll look something like this (var/tmp-GOPO01/lib/x86_64-linux-gnu/), does that have the .so.1.0 in it?

**Comment by kaneyumin** [comment]
Nope it isn't in there

**Comment by d10sfan** [comment]
Interesting, it is there for me. If you manually create a symlink (to make a libbz.so.1.0) in either of those directories does it make the game work?

I should be able to add a workaround to the launch, so was curious

**Comment by kaneyumin** [comment]
seems to still give me the same issue

**Comment by kaneyumin** [comment]
What should the resource line in openmw.cfg be? Maybe if I change it to its proper location it'll work.

**Comment by d10sfan** [comment]
https://github.com/luxtorpeda-dev/packages/commit/5c7ed2d1aef94d9cdf0b3b56cf1bce1f775ecda5

I've committed a possible fix that creates a link to the library in the game dir, it'll be live in a few hours (when this action is complete - https://github.com/luxtorpeda-dev/packages/actions/runs/4229019772).

Let me know how that goes for you!

**Comment by kaneyumin** [comment]
Unfortunately it still doesn't work. 

Oh well, maybe it's on my end. I appreciate the help in trying to get it fixed.

**Comment by d10sfan** [comment]
Strange, could you provide a new log, where you remove the config file and then run? Curious where it's stopping.

I haven't tried your distro before, so there maybe something unique there.

**Comment by kaneyumin** [comment]
>20:48:26 [INFO] install: "mkspecs/win32-g++/qplatformdefs.h"
20:48:26 [INFO] install: "mkspecs/solaris-g++"
20:48:26 [INFO] install: "mkspecs/solaris-g++/qmake.conf"
20:48:26 [INFO] install: "mkspecs/solaris-g++/qplatformdefs.h"
20:48:26 [INFO] install: "mkspecs/win32-arm64-msvc2017"
20:48:26 [INFO] install: "mkspecs/win32-arm64-msvc2017/qmake.conf"
20:48:26 [INFO] install: "mkspecs/win32-arm64-msvc2017/qplatformdefs.h"
20:48:26 [INFO] install: "mkspecs/solaris-cc-64-stlport"
20:48:26 [INFO] install: "mkspecs/solaris-cc-64-stlport/qmake.conf"
20:48:26 [INFO] install: "mkspecs/solaris-cc-64-stlport/qplatformdefs.h"
20:48:26 [INFO] install: "mkspecs/qmodule.pri"
20:48:26 [INFO] install: "mkspecs/winrt-arm-msvc2015"
20:48:26 [INFO] install: "mkspecs/winrt-arm-msvc2015/qmake.conf"
20:48:26 [INFO] install: "mkspecs/winrt-arm-msvc2015/qplatformdefs.h"
20:48:26 [INFO] install: "mkspecs/freebsd-clang"
20:48:26 [INFO] install: "mkspecs/freebsd-clang/qmake.conf"
20:48:26 [INFO] install: "mkspecs/freebsd-clang/qplatformdefs.h"
20:48:26 [INFO] run: "./openmw.sh" with args: [] []
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
openmw.cfg file detected, so checking for resources
resources line found
./openmw: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
20:48:26 [INFO] run returned with exit status: 127
Game process removed: AppID 22320 "LUX_WRITE_LOGGING=1 /home/kane/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=22320 -- /home/kane/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- '/home/kane/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'/_v2-entry-point --verb=waitforexitandrun -- '/home/kane/.local/share/Steam/compatibilitytools.d/luxtorpeda'/luxtorpeda.sh waitforexitandrun  '/home/kane/.local/share/Steam/steamapps/common/Morrowind/Morrowind Launcher.exe'", ProcID 15448 

same error i think

**Comment by d10sfan** [comment]
Weird, I was hoping this line would fix it: ```ln -rsf /lib/x86_64-linux-gnu/libbz2.so.1.0.4 ./lib/libbz2.so.1.0```

If you end up finding anything that fixes it, please let me know and I can update it.

**Comment by Jpxe** [comment]
I just wanted to say that I'm also on Nobara 37 and it runs fine for me. Let me know if I can help test anything

**Comment by d10sfan** [comment]
Thanks! Out of curiosity, do either of you have libbz2 installed as a system package? I'm not sure why this is an issue, since the runtime is supposed to provide it, but curious if that may explain why it works for you.

**Comment by kaneyumin** [comment]
I installed it when I saw the error about missing it.

**Comment by kaneyumin** [comment]
@Jpxe Could I see your openmw.cfg in ~/.config/openmw? I'd like to check something

**Comment by kaneyumin** [comment]
I was trying some other games supported by luxtorpeda. Some of them work but I found the same issue with running Shadow Warrior.

>23:03:43 [INFO] install: "lib/libzmusic.so"
23:03:43 [INFO] install: "raze_template.ini"
23:03:43 [INFO] install: "raze.pk3"
23:03:43 [INFO] run: "./run-raze.sh" with args: [] ["-conf", "dosbox_swarrior.conf", "-conf", "dosbox_swarrior_single.conf", "-noconsole", "-c", "exit"]
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
./raze: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory
23:03:43 [INFO] run returned with exit status: 127

So I guess there's some issue on my end

**Comment by kaneyumin** [comment]
I was taking another look at 

>/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6

and realized that the file it pointed it was in the wrong path on my machine. 
it pointed to 
>/run/host/usr/lib64/libtinfo.so.6.3

while the file on my machine was in

>[kane@kane-pc ~]$ locate libtinfo.so.6
/home/kane/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20230117.0/files/lib/i386-linux-gnu/libtinfo.so.6.1
/home/kane/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/soldier_platform_0.20230117.0/files/lib/x86_64-linux-gnu/libtinfo.so.6.1
/usr/lib/libtinfo.so.6
/usr/lib/libtinfo.so.6.3
/usr/lib64/libtinfo.so.6
/usr/lib64/libtinfo.so.6.3
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/3616ca621531deb9904cb2ebe436211609d503e481122f57a50067ecb9979e63/files/lib/x86_64-linux-gnu/libtinfo.so.6
/var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/22.08/3616ca621531deb9904cb2ebe436211609d503e481122f57a50067ecb9979e63/files/lib/x86_64-linux-gnu/libtinfo.so.6.3
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.15-21.08/2e4ed12dc21144c4bd7bcef988d74b8f079a50258dce3a433a880e6b2196fc76/files/lib/x86_64-linux-gnu/libtinfo.so.6
/var/lib/flatpak/runtime/org.kde.Platform/x86_64/5.15-21.08/2e4ed12dc21144c4bd7bcef988d74b8f079a50258dce3a433a880e6b2196fc76/files/lib/x86_64-linux-gnu/libtinfo.so.6.2

The same issue was with libbz2.so.1.0. 
I can't change the path for the link as the tmp folder generates each time the game is run. Would it be possible to change the paths in some way?
